[features]
seeds = false

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"


[programs.localnet]
example1 = "75qoKtT4w6ysfWt8Y9ejzSNBe819sU5A1D7dsWLcQutY" 

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
